# budget.yaml — one AWS Budget per app in THIS env directory.
# Enums mirror AWS API/console.

enabled: true

budgets:
  - app_name: insizon
    limit_amount: 25
    limit_unit: USD
    budget_type: COST
    time_unit: MONTHLY
    start_date: "2024-01-01_00:00"
    threshold: 80
    comparison_operator: GREATER_THAN
    threshold_type: PERCENTAGE
    notification_type: ACTUAL
    email_recipients:
      - lamonte.scott@insizon.com
