# rds.yaml (PROD)
# Purpose: Production PostgreSQL RDS
# Verify networking IDs are correct in the prod account/region before apply.

enabled: false

rds:
  engine_version: "17.5"

  sizing:
    instance_class: "db.m6g.large"
    multi_az: true
    allocated_storage: 200
    backup_retention: 14

  vpc_id: "vpc-0ea9888b4bd62ccb4"
  subnet_ids: ["subnet-0927b9c05b9fcf0d0", "subnet-0d3cef8a0ebac1db9"]
  sg_ids: ["sg-0026487553bf7472a"]

  db_name: "appdb"
  username_ssm: "insizon-rds-username"
  password_ssm: "insizon-rds-password"
