############################################################
# variables.tf – public API of the iam/users module
############################################################

variable "user_name" {
  description = "IAM user name (must be unique per AWS account)"
  type        = string
}

variable "create_console_password" {
  description = "Set to true to create an AWS console password"
  type        = bool
  default     = false
}

variable "password_length" {
  description = "Length of autogenerated console password"
  type        = number
  default     = 20
}

variable "policy_arns" {
  description = "List of AWS managed (or custom) policy ARNs to attach"
  type        = list(string)
  default     = []
}

variable "tags" {
  description = "Custom tags to apply to the IAM user"
  type        = map(string)
  default     = {}
}

variable "pgp_key" {
  description = <<EOT
Optional PGP public key (ASCII-armored).
If supplied, the secret access key is encrypted client-side and the
encrypted blob is stored in state. Recommended for production.
EOT
  type        = string
  default     = ""
}
