# budget.yaml ────────────────────────────────────────────────────────────
# One AWS Budget per app/env.  All enum values mirror the AWS Console.
# Any omitted key falls back to the default shown below.

budgets:
  - app_name: insizon
    env: dev

    # ---- Core limit ----------------------------------------------------
    limit_amount: 30            # numeric string or number, unit = limit_unit
    limit_unit: USD             # USD | EUR | etc.
    budget_type: COST           # COST | USAGE | RI_COVERAGE | etc.
    time_unit: MONTHLY          # DAILY | MONTHLY | QUARTERLY | ANNUALLY
    start_date: "2024-01-01_00:00"

    # ---- Alert settings -----------------------------------------------
    threshold: 80               # 80 %
    comparison_operator: GREATER_THAN   # < | >
    threshold_type: PERCENTAGE  # PERCENTAGE | ABSOLUTE_VALUE
    notification_type: ACTUAL   # ACTUAL | FORECASTED
    email_recipients:           # fallback = alerts@<app>.com
      - alerts@insizon.com
