# cloudfront.yaml ────────────────────────────────────────────────────────
# CloudFront key-group inventory.  One entry can serve many apps.
# Keys
# ── key_group_name : **Required** unique label (matches apps.yaml)
# ── keys           : List of public-key *filenames* (without ".pem") that
#                     live under private/cloudfront/rsa_keys/public/.
#                     ⚠️ Keep the list ≤100 or Terraform will fail.
# ── apps           : Convenience list to note which apps expect this group
#                     (not consumed by TF—but great for human auditing).

cloudfront_key_groups:
  - key_group_name: dev-key-group
    keys:
      - insizon-app-dev
    default_root_object: index.html
    price_class: PriceClass_All
    viewer_protocol_policy: redirect-to-https
    allowed_methods:
      - GET
      - HEAD
      - OPTIONS
    cached_methods:
      - GET
      - HEAD
    geo_restriction:
      restriction_type: whitelist
      locations:
        - US
        - CA
    apps:
      - insizon-app:dev
