# ecr.yaml ───────────────────────────────────────────────────────────────
# ECR repo per app/env.  If create_service=false we skip provisioning.

ecr:
  - app_name: insizon-app
    env: dev
    service_name: insizon-app          # optional override; default = app_name
    create_service: true
    scan_on_push: true
    lifecycle_policy: "retain-last-20" # placeholder for future use
