# elasticbeanstalk.yaml ──────────────────────────────────────────────────
# Beanstalk environment definitions.

beanstalk:
  - app_name: insizon-app
    env: dev
    service_name: insizon-app            # default = app_name
    create_service: true

    # Platform string must match `aws elasticbeanstalk list-available-solution-stacks`
    platform: "64bit Amazon Linux 2023 v6.5.2 running Node.js 22"

    tier: WebServer                      # WebServer | Worker

    # Optional additional settings per language stack can go here later.
    env_vars:
      API_KEY: abc123
      NODE_ENV: production
