# static-files.yaml ──────────────────────────────────────────────────────
# Controls which files/folders the static-upload module will push to S3.

static_files:
  - app_name: insizon-app
    env: dev

    # Sub-folder inside private/static_bucket/<app>-<env>/ to upload.
    # Default = "public"
    folder_name: public

    # List of glob patterns or exact filenames to *skip*.
    files_excluded:
      - photo.png
