# user-roles.yaml ────────────────────────────────────────────────────────
# NOTE: Field names kept in camelCase because existing HCL already
# expects them.  Feel free to snake_case later—just remember to update
# locals.tf accordingly.
# roles - admin | developer | readOnly | serviceAccount
# types - privileged | readonly
# limit - Restricts access to listed app_name from apps.yaml file
# Note: userNames must be lowercase and only use (-) special character

users:
# ─────────────────────────────────────────────────────────────────────
  - userName: service-account-insizon
    fullName: Service Account Insizon
    roles: [serviceAccount]
    type: privileged
    limit:
      - insizon
      # - insizon-qa
      # - insizon-prod
# ─────────────────────────────────────────────────────────────────────
  - userName: insizonxcontractor
    fullName: Insizon Contractor Developer
    roles: [developer]
    type: privileged
    limit:
      - insizonxcontractor
  # # ─────────────────────────────────────────────────────────────────────
  # - userName:  service-account-maxgeneye
  #   fullName: Service Account Maxgeneye
  #   roles: [serviceAccount]
  #   type: privileged
  #   limit:
  #     - maxgeneye-dev
  #     # - maxgeneye-qa
  #     - maxgeneye-prod
  # # ─────────────────────────────────────────────────────────────────────
  # - userName: lamonte-scott
  #   fullName: Lamonte Scott
  #   roles: [admin]
  #   type: privileged
  #   limit:
  #     - insizon-dev
  #     - maxgeneye-dev
  # # ─────────────────────────────────────────────────────────────────────
  # - userName: maxgeneyexcontractor
  #   fullName: Maxgeneye Contractor Developer
  #   roles: [developer]
  #   type: privileged
  #   limit:
  #     - maxgeneyexcontractor-dev
  # # ─────────────────────────────────────────────────────────────────────
  # - userName: user-sara-banks
  #   fullName: Sara Banks
  #   roles: [readOnly]
  #   type: privileged
  #   limit:
  #     - insizon-dev